### ISSUE TITLE
Check if filetype exists

### ISSUE THREAD

**Issue by madeleineostoja** [seaneking/postcss-fontpath#2]
~~Users should be able to define what font formats the output generates.~~

Plugin should check if given filetype exists before adding to src set. Straightforward to do, only nonstandard logic is checking `eot` separately for ie hack.

**Comment by masi** [comment]
Perhaps. But better would be that the generator tests if a file with a given extension exists before it adds the path to the CSS code.

**Comment by madeleineostoja** [comment]
Yep agreed, and it wouldn't be that difficult to do. Changing this issue to reflect.

**Comment by lukelarsen** [comment]
I'd love to see this.

**Comment by madeleineostoja** [comment]
Fixed in https://github.com/seaneking/postcss-fontpath/pull/5
