### ISSUE TITLE
Issue when font-path is defined with double quote

### ISSUE THREAD

**Issue by hroblesm** [seaneking/postcss-fontpath#7]
Hi ,

I found an issue  when the font-path is defined with double quote:

@font-face {
  font-family: "My Font";
  font-path: "/path/to/font/file";
  ...
}
It generates as follows:

@font-face {
  font-family: "My Font";
  src: url(""/path/to/font/file".eot");
   ...
}

**Comment by madeleineostoja** [comment]
Fixed in #9
