### ISSUE TITLE
Trailing comma and missing font file when only woff file availible

### ISSUE THREAD

**Issue by mikestreety** [seaneking/postcss-fontpath#8]
When only having the `woff` file in the folder and the `checkPath` option enabled, slightly incorrect (and invalid) CSS is generated:

```
@font-face {
    font-family: 'Proxima Nova';
    src: url(../fonts/proximanova-regularit-webfont.eot);
    src: url(../fonts/proximanova-regularit-webfont.woff) format('woff'),;
    font-weight: 400;
    font-style: italic
}
```

Note the `eot` is still included and the extra comma after `('woff')`. Does https://github.com/seaneking/postcss-fontpath/pull/4 address these issues?

**Comment by mikestreety** [comment]
### Update:

#### Trailing Comma

- It **does not** have a trailing comma when there is `woff` and `svg` files
- It **does** have a trailing comma when there is `woff` and `ttf`
- It **does** have a trailing comma when there is only a `ttf`
- It **does not** have the trailing comma when there is only SVG files

#### Other
- ~It **does not** seem to pick up and include our `woff2` files~ (this is due to it not being release since the addition)
- Where there are _no_ files found, it **does not** include the `eot` IE fix

**Comment by mikestreety** [comment]
Believe the trailing comma is added on everything except the SVG becuase SVG is at the end of the formats array.

I think at [this point](https://github.com/seaneking/postcss-fontpath/blob/master/index.js#L45) it needs to remove the unfound font format from the array, so that the following comma check can be correct.

It should only add the `eot` IE font fix if an `eot` is found. 

I'm sorry, I don't know enough node/post-css to confidently do a pull request. 😥

**Comment by mikestreety** [comment]
I've noticed that there is no `woff2` because it was added after the last version was released.

**Comment by mikestreety** [comment]
@seaneking Hey, any chance to look at this? I appreciate we are all busy in lives!

If you no longer maintain this, then I will look at alternative solutions (or try fixing) - if it's on your radar then I appologise for bothering you!

**Comment by madeleineostoja** [comment]
Whoops sorry missed this. I'm flat out at the moment, but will see if I can have a quick look later today.

**Comment by mikestreety** [comment]
Not a problem, thank you!

**Comment by madeleineostoja** [comment]
Okay had a poke around, but this plugin really needs to be refactored, I haven't touched it in years. Not going to have time to do that right now, in the meantime you can just turn off `checkPaths`, you'll get a valid declaration then, with just a few unused src props (if you have woff2 fonts then there wont be any additional requests made by the browser).

Sorry. More than happy to accept a PR if you want to have a go yourself.
